import Head from 'next/head';
import Footer from '../components/Footer';
import NavBar from '../components/NavBar';
import Clients from './clients';
import Contact from './contact';
import HomePage from './homePage';
import Services from './services';
import Work from './work';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <HomePage />
      <Services />
      <Work />
      <Clients />
      <Contact />
      <Footer />
      
    </div>
  )
}
